test: simulate failed build

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -24,7 +24,9 @@ jobs:
    - name: lint
      run: npm run eslint
    - name: build
-     run: npm run build
+     run: |
+      npm run build
+      exit 1  # Force the build to fail
    - name: Build failed
      if: ${{ failure() }}   
      env:
